# Generated by Django 4.2.7 on 2025-09-12 20:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_add_results_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='split',
            options={'ordering': ['split_time']},
        ),
        migrations.AlterUniqueTogether(
            name='split',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='result',
            name='chip_time',
            field=models.DurationField(blank=True, help_text='Chip/net time', null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='time_behind',
            field=models.DurationField(blank=True, help_text='Time behind winner', null=True),
        ),
        migrations.AddField(
            model_name='split',
            name='split_name',
            field=models.CharField(default='', help_text="Name of the split point (e.g., 'Hafravatn')", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='participant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='split',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='split',
            name='split_time',
            field=models.DurationField(help_text='Cumulative time from start to this split'),
        ),
        migrations.AlterUniqueTogether(
            name='split',
            unique_together={('result', 'split_name')},
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nationality', models.CharField(default='ISL', help_text='ISO 3166-1 alpha-3 country code', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='races_runne_name_d41f77_idx'), models.Index(fields=['birth_year'], name='races_runne_birth_y_8e8681_idx'), models.Index(fields=['name', 'birth_year'], name='races_runne_name_d5b640_idx')],
                'unique_together': {('name', 'birth_year')},
            },
        ),
        migrations.RemoveField(
            model_name='split',
            name='cumulative_time',
        ),
        migrations.AddField(
            model_name='result',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.runner'),
        ),
    ]
