# Generated by Django 4.2.7 on 2025-09-12 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_add_runner_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Event name as found on timataka.net homepage', max_length=200)),
                ('date', models.DateField(help_text='Event date parsed from homepage')),
                ('url', models.URLField(help_text='URL to the event page on timataka.net', unique=True)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('processed', 'Processed'), ('error', 'Error')], default='discovered', max_length=20)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='races_event_date_a13dbe_idx'), models.Index(fields=['status'], name='races_event_status_3f35c7_idx'), models.Index(fields=['url'], name='races_event_url_3ad3f1_idx')],
            },
        ),
        migrations.AddField(
            model_name='race',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races', to='races.event'),
        ),
    ]
