# Generated by Django 4.2.7 on 2025-09-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_event_race_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['finish_time']},
        ),
        migrations.RemoveIndex(
            model_name='result',
            name='races_resul_race_id_1ea091_idx',
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['race', 'finish_time'], name='races_resul_race_id_8b4a93_idx'),
        ),
        migrations.RemoveField(
            model_name='result',
            name='age_group_place',
        ),
        migrations.RemoveField(
            model_name='result',
            name='gender_place',
        ),
        migrations.RemoveField(
            model_name='result',
            name='overall_place',
        ),
    ]
