# Generated by Django 4.2.7 on 2025-09-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_remove_placement_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='gender',
        ),
    ]
