# Generated by Django 4.2.7 on 2025-09-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_move_gender_to_runner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cached_html',
            field=models.TextField(blank=True, help_text='Cached HTML content from the event page'),
        ),
        migrations.AddField(
            model_name='event',
            name='html_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the HTML was last fetched', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='cached_html',
            field=models.TextField(blank=True, help_text='Cached HTML content from the results page'),
        ),
        migrations.AddField(
            model_name='race',
            name='html_fetched_at',
            field=models.DateTimeField(blank=True, help_text='When the HTML was last fetched', null=True),
        ),
    ]
