# Generated by Django 4.2.7 on 2025-09-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_event_cached_html_event_html_fetched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='error_count',
            field=models.IntegerField(default=0, help_text='Number of consecutive errors encountered'),
        ),
        migrations.AddField(
            model_name='race',
            name='has_server_error',
            field=models.BooleanField(default=False, help_text='True if the race results page returns server errors (500, 404, etc.)'),
        ),
        migrations.AddField(
            model_name='race',
            name='last_error_at',
            field=models.DateTimeField(blank=True, help_text='When the last error occurred', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='last_error_code',
            field=models.IntegerField(blank=True, help_text='Last HTTP error code encountered', null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='last_error_message',
            field=models.TextField(blank=True, help_text='Last error message encountered'),
        ),
    ]
