# Generated by Django 4.2.7 on 2025-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_add_error_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('timataka.net', 'Timataka.net'), ('corsa.is', 'Corsa.is')], default='timataka.net', help_text='Source website', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='source',
            field=models.CharField(choices=[('timataka.net', 'Timataka.net'), ('corsa.is', 'Corsa.is')], default='timataka.net', help_text='Source website', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event date parsed from the website'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Event name as found on the results website', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(help_text='URL to the event page', unique=True),
        ),
    ]
